# exp_010 | coordinate 20dbbcced245 | generated by the Worker Agent; executed by the simulator
from __future__ import annotations

import math
import torch
import torch.nn as nn

# ---------------------------------------------------------------------------
# Features: reference_35 = reference featurizer (33 values) + 2 extras
# ---------------------------------------------------------------------------

FEATURE_NAMES = [
    "util", "headroom", "tool_frac", "redundancy", "stale", "confidence", "phase", "since_instr",
    "since_compact", "error_streak", "last_error", "recall_miss", "topic_shift", "util_delta",
    "growth_ema", "steps_to_overflow", "pressure", "salience_est", "integrity_est", "recall_intensity",
    "loop_persistence", "streak_pressure", "tool_rate", "shift_rate", "cliff_margin", "required_rate",
    "recent_success", "last_a0", "last_a1", "last_a2", "last_a3", "last_a4", "last_a5",
    "progress_to_threshold", "error_streak_decay",
]

N_ACTIONS = 6


def _clip(v, lo, hi):
    if v < lo:
        return lo
    if v > hi:
        return hi
    return v


def featurize(history):
    try:
        o = history[-1]
        n = len(history)
        util = float(o.get("utilization", 0.0))
        prev_util = float(history[-2]["utilization"]) if n > 1 else util
        ema = 0.0
        for h in history[-8:]:
            ema = 0.7 * ema + 0.3 * float(h.get("tokens_added_last", 0.0))
        sal, integ = 1.0, 1.0
        errs, err_after_err, prev_err = 0, 0, 0
        recalls = sum(int(h.get("recall_miss", 0)) for h in history)
        step = int(o.get("step", 0))
        ri = recalls / max(1, step)
        tools = shifts = 0
        prev_tool = 0.0
        for h in history[1:]:
            a = int(h.get("last_action", 0))
            if a == 3:
                sal = 1.0
            else:
                sal = sal * math.exp(-0.04 * (0.5 + float(h.get("utilization", 0.0))))
            if h.get("topic_shift", 0):
                sal *= 0.9
            if a == 1:
                integ *= 1 - 0.35 * min(1.0, 3 * ri)
            elif a == 2:
                integ *= 1 - 0.12 * min(1.0, 3 * ri)
            elif a == 4:
                integ *= 1 - 0.5 * min(1.0, 3 * ri)
            elif a == 5:
                integ = min(1.0, integ + 0.6)
            if h.get("last_error", 0):
                errs += 1
                err_after_err += prev_err
            prev_err = int(h.get("last_error", 0))
            tt = float(h.get("tool_tokens", 0.0))
            tools += int(tt > prev_tool + 0.5)
            prev_tool = tt
            shifts += int(h.get("topic_shift", 0))
        steps = max(1, step)
        loop_p = err_after_err / max(1, errs)
        recent = history[-6:]
        rs = sum(int(h.get("last_success", 0)) for h in recent) / max(1, len(recent))
        horizon = float(o.get("horizon", 40))
        remaining = horizon - step
        progress = float(o.get("progress", 0))
        last_action = int(o.get("last_action", 0))
        la = [0.0] * 6
        if 0 <= last_action < 6:
            la[last_action] = 1.0

        capacity = float(o.get("capacity", 128.0))
        tokens_used = float(o.get("tokens_used", 0.0))
        error_streak = float(o.get("error_streak", 0))

        feats = [
            util, 1 - util, float(o.get("tool_fraction", 0.0)), float(o.get("redundancy_est", 0.0)),
            float(o.get("stale_est", 0.0)), float(o.get("confidence", 0.0)),
            step / max(1.0, horizon), float(o.get("steps_since_instruction", 0)) / 40.0,
            float(o.get("steps_since_compaction", 0)) / 40.0,
            min(error_streak, 6) / 6, float(o.get("last_error", 0)), float(o.get("recall_miss", 0)),
            float(o.get("topic_shift", 0)), util - prev_util,
            ema / 10.0, min(40.0, (capacity - tokens_used) / max(0.5, ema)) / 40.0,
            max(0.0, util - 0.55) / 0.45, sal, integ, ri, loop_p,
            min(error_streak, 5) / 5 * loop_p,
            tools / steps, shifts / steps,
            (progress + rs * remaining - 24) / 4,
            (24 - progress) / max(1, remaining), rs,
        ] + la

        progress_to_threshold = _clip((24 - progress) / 24.0, -1.0, 1.0)
        decay_mul = 0.5 if last_action in (1, 3) else 1.0
        error_streak_decay = error_streak * decay_mul

        feats.append(progress_to_threshold)
        feats.append(error_streak_decay)

        out = []
        for v in feats:
            fv = float(v)
            if not math.isfinite(fv):
                fv = 0.0
            out.append(fv)
        if len(out) != len(FEATURE_NAMES):
            out = (out + [0.0] * len(FEATURE_NAMES))[: len(FEATURE_NAMES)]
        return out
    except Exception:
        return [0.0] * len(FEATURE_NAMES)


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

NOOP_MARGIN_STRENGTH = 0.75  # noop_margin_strength coordinate value


class MLPWithCalibration(nn.Module):
    def __init__(self, input_dim, n_actions, hidden=(64, 64), noop_margin=0.0):
        super().__init__()
        layers = []
        prev = input_dim
        for h in hidden:
            layers.append(nn.Linear(prev, h))
            layers.append(nn.ReLU())
            prev = h
        layers.append(nn.Linear(prev, n_actions))
        self.body = nn.Sequential(*layers)
        self.noop_margin = float(noop_margin)

    def forward(self, x):
        logits = self.body(x)
        if self.noop_margin != 0.0:
            bias = torch.zeros_like(logits)
            bias[:, 0] = -self.noop_margin
            logits = logits + bias
        return logits


def build_model(input_dim, n_actions):
    return MLPWithCalibration(
        input_dim, n_actions, hidden=(64, 64), noop_margin=NOOP_MARGIN_STRENGTH
    )


# ---------------------------------------------------------------------------
# Training configuration
# ---------------------------------------------------------------------------

TRAIN_CONFIG = {
    "lr": 5e-4,
    "epochs": 30,
    "batch_size": 256,
    "optimizer": "adamw",
    "weight_decay": 0.01,
    "grad_clip": 1.0,
    "standardize": True,
    "teacher": "v2",
    "target": "soft",
    "target_temperature": 0.5,
    "data": "behaviour+self",
    "self_episodes": 84,
    "ensemble_seeds": 3,
    "early_stop": "val_regret",
}
